vocab = ['[END]', '[NH1]', '[Branch1_3expl]', '[O+1]', '[=SHexpl]', '[Nexpl]', '[#N]', '[Cl+3]', '[F-1]', '[N]', '[Feexpl]', '[Ring1expl]', 
 '[BH3-1]', '[\\C]', '[Coexpl]', '[=Branch2]', '[Ring2expl]', '[Oexpl]', '[O+expl]', '[\\N]', '[#C-1]', '[=Ring2]', '[Seexpl]', '[Cl+2]', 
 '[NH2+expl]', '[Branch2_2]', '[=N+expl]', '[S-expl]', '[P+1]', '[N+explexpl]', '[Brexpl]', '[S+expl]', '[=SH1]', '[Expl=Ring2]', '[=Si]', 
 '[Fexpl]', '[C+1]', '[NH2+1]', '[O-expl]', '[B]', '[Branch2_2expl]', '[Branch1_1]', '[S]', '[Ptexpl]', '[SiH1-1]', '[18Fexpl]', '[Branch1_2]', 
 '[=O+1]', '[O-explexpl]', '[B-1]', '[N-expl]', '[Ring1]', '[=B]', '[Branch2_3]', '[Cuexpl]', '[CH1+1]', '[Si-1]', '[=C]', '[#O+1]', '[=OH1+1]', 
 '[I+1]', '[I+3]', '[CH-expl]', '[Branch2_1expl]', '[=S+1]', '[#N+1]', '[Se]', '[Ring2]', '[=O]', '[=Se+1]', '[PH2+1]', '[Naexpl]', '[Branch2]', 
 '[C@Hexplexpl]', '[Br+2]', '[BH1-1]', '[Sexpl]', '[Cl-1]', '[Branch1_2expl]', '[CH1]', '[P]', '[Se-1]', '[C@@Hexpl]', '[Cl]', '[F]', '[=OH+expl]', 
 '[Hgexpl]', '[Pexpl]', '[\\C@@Hexpl]', '[CH2expl]', '[35Sexpl]', '[=NH+expl]', '[Siexpl]', '[/C]', '[=Ring1]', '[=Se]', '[C@expl]', '[Fe-2expl]', 
 '[CH2explexpl]', '[NH3+expl]', '[CH2]', '[PH1]', '[=O+expl]', '[Expl=Ring1]', '[SiH1]', '[PHexpl]', '[AsHexpl]', '[Ring3]', '[#C-expl]', '[SHexpl]', 
 '[S@expl]', '[2Hexpl]', '[\\C@Hexpl]', '[Biexpl]', '[BH0]', '[C@@expl]', '[Oexplexpl]', '[NH1+1]', '[Cexpl]', '[Asexpl]', '[I]', '[SH1]', '[Branch1_1expl]', 
 '[CH1-1]', '[=N]', '[=NH1+1]', '[SeH1]', '[/N+expl]', '[O]', '[C+expl]', '[\\O]', '[NHexpl]', '[N+expl]', '[C]', '[=PH1]', '[N-1]', '[Sbexpl]', '[#C]', 
 '[Srexpl]', '[NH-expl]', '[Cl+1]', '[OH0]', '[/O]', '[Branch1]', '[NH+expl]', '[#N+expl]', '[=N-1]', '[S+1]', '[C-expl]', '[#Branch2]', '[NH0]', '[\\Cl]', 
 '[C@Hexpl]', '[=C-1]', '[N+1]', '[Branch3_1]', '[Si]', '[/S]', '[CHexpl]', '[S+explexpl]', '[=N+1]', '[Br]', '[C@@Hexplexpl]', '[NH3+1]', '[START]', '[NH1-1]', 
 '[Feexplexpl]', '[H]', '[O-1]', '[P+expl]', '[C-1]', '[SeH2]', '<stop>', '[Siexplexpl]', '[Br-1]', '[Branch2_3expl]', '[Branch1_3]', '[=NH2+1]', '[F+1]', 
 '[Branch2_1]', '[=S]', '[S-1]', '[Clexpl]', '[/C@Hexpl]', '[Caexpl]', '[CH2+1]', '[=S+expl]', '<start>', '[Znexpl]', '[Se+1]', '[I+2]', '[=N-expl]', '[BH2-1]', 
 '[nop]', '[#Branch1]', '[/C@@Hexpl]', '[=Branch1]', '[SiH2]', '[AlH3expl]', '[Auexpl]', '[/N]', '[Kexpl]', '[PbH2expl]', '[=P]']